-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS AS A
JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE SUBSTR(A.SEX_UPON_INTAKE,1,7) = 'Intact'
AND (SUBSTR(B.SEX_UPON_OUTCOME,1,9) = 'Neutered'
OR SUBSTR(B.SEX_UPON_OUTCOME,1,7) = 'Spayed')
ORDER BY A.ANIMAL_ID ASC;